[package]
name = "cargo-feature-matrix"
authors = ["person93 <person93.person93@gmail.com>"]
version = "0.1.0-dev"
edition = "2021"
description = "run cargo commands on a matrix of feature sets"
license = "MIT"

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["wrap_help"] }
derive_more = "0.99.17"
serde = { version = "1.0.130", features = ["derive"] }
